"""Codex-specific workspace configuration generation."""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any


logger = logging.getLogger("k_agent.runners.codex.config")


def write_codex_mcp_config(
    workspace: Path, mcp_servers: Sequence[dict[str, Any]]
) -> Path | None:
    """Write Codex TOML without involving another CLI provider's config."""

    if not mcp_servers:
        return None
    lines = ["# Auto-generated by k_agent — do not edit manually"]
    count = 0
    for server in mcp_servers:
        server_id = str(server.get("id") or "").strip()
        if not server_id:
            continue
        transport = str(server.get("type") or "stdio")
        if transport in {"http", "sse"}:
            url = server.get("url")
            if not url:
                continue
            lines.append(f"\n[mcp_servers.{_toml_key(server_id)}]")
            lines.append(f"url = {_toml_string(url)}")
            if server.get("bearerTokenEnv"):
                lines.append(
                    "bearer_token_env_var = "
                    f"{_toml_string(server['bearerTokenEnv'])}"
                )
        else:
            command = server.get("command")
            if not command:
                continue
            lines.append(f"\n[mcp_servers.{_toml_key(server_id)}]")
            lines.append(f"command = {_toml_string(command)}")
            args = server.get("args")
            if args:
                lines.append(
                    "args = ["
                    + ", ".join(_toml_string(str(arg)) for arg in args)
                    + "]"
                )
            env = server.get("env")
            if isinstance(env, dict) and env:
                lines.append(f"[mcp_servers.{_toml_key(server_id)}.env]")
                for key, value in env.items():
                    lines.append(f"{key} = {_toml_string(str(value))}")
            if server.get("cwd"):
                lines.append(f"cwd = {_toml_string(str(server['cwd']))}")
        count += 1
    if count == 0:
        return None
    config_dir = workspace / ".codex"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.toml"
    marker_start = "# >>> k_agent managed MCP servers >>>"
    marker_end = "# <<< k_agent managed MCP servers <<<"
    managed_block = f"{marker_start}\n" + "\n".join(lines) + f"\n{marker_end}\n"
    existing = config_path.read_text(encoding="utf-8") if config_path.is_file() else ""
    if marker_start in existing:
        existing = re.sub(
            re.escape(marker_start) + r".*?" + re.escape(marker_end) + r"\n?",
            "",
            existing,
            flags=re.DOTALL,
        )
    merged = existing.rstrip() + ("\n\n" if existing.strip() else "") + managed_block
    config_path.write_text(merged, encoding="utf-8")
    logger.debug("Wrote Codex MCP config with %d server(s) to %s", count, config_path)
    return config_path


def _toml_string(value: Any) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_key(name: str) -> str:
    return name if re.fullmatch(r"[A-Za-z0-9_-]+", name) else _toml_string(name)
