"""Declarative Agent observers and execution middleware."""

from backend.agent.hooks.decorators import (
    after_agent,
    after_model,
    before_agent,
    before_model,
    observe,
    wrap_model_call,
    wrap_tool_call,
)
from backend.agent.hooks.observers import ObserverDispatcher, TraceObserver
from backend.agent.hooks.pipeline import AgentPipelineDefinition, AgentPipelineRuntime
from backend.agent.hooks.types import (
    AgentCompletedEvent,
    AgentErrorPayload,
    AgentEvent,
    AgentEventType,
    AgentRunContext,
    AgentStartedEvent,
    ContextBuiltEvent,
    ContextPlanPayload,
    ContextPrunedEvent,
    ContextPrunePayload,
    FailureMode,
    HookKind,
    HookSpec,
    ModelCallPayload,
    ModelCallCompleted,
    ModelCompletedEvent,
    ModelReasoningDelta,
    ModelResultPayload,
    ModelStreamEvent,
    ModelStartedEvent,
    ModelTextDelta,
    OperationFailedEvent,
    ToolCallPayload,
    ToolCallRequest,
    ToolCallResult,
    ToolCompletedEvent,
    ToolResultPayload,
    ToolStartedEvent,
)

__all__ = [
    "AgentCompletedEvent",
    "AgentErrorPayload",
    "AgentEvent",
    "AgentEventType",
    "AgentPipelineDefinition",
    "AgentPipelineRuntime",
    "AgentRunContext",
    "AgentStartedEvent",
    "ContextBuiltEvent",
    "ContextPlanPayload",
    "ContextPrunedEvent",
    "ContextPrunePayload",
    "FailureMode",
    "HookKind",
    "HookSpec",
    "ModelCallPayload",
    "ModelCallCompleted",
    "ModelCompletedEvent",
    "ModelReasoningDelta",
    "ModelResultPayload",
    "ModelStreamEvent",
    "ModelStartedEvent",
    "ModelTextDelta",
    "ObserverDispatcher",
    "OperationFailedEvent",
    "ToolCallPayload",
    "ToolCallRequest",
    "ToolCallResult",
    "ToolCompletedEvent",
    "ToolResultPayload",
    "ToolStartedEvent",
    "TraceObserver",
    "after_agent",
    "after_model",
    "before_agent",
    "before_model",
    "observe",
    "wrap_model_call",
    "wrap_tool_call",
]
